#!/bin/bash

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
protected_branches=( master main )

for i in "${protected_branches[@]}"; do
    if [[ $i == "$current_branch" ]]; then
      echo 'Attention! You are pushing to a protected branch. Running tests and linting...'

      ./gradlew test
      if [ $? -ne 0 ]; then
        echo 'Aborting push (Cannot push when the test suite fails)'
        exit 1
      fi

      ./gradlew check -x test
      if [ $? -ne 0 ]; then
        echo 'Aborting push (Cannot push when the style check fails)'
        exit 1
      fi
    fi
done

exit 0
