spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unicorn-service
    username: unicorn-service
    password: d4nc31ng0nR41nb0w5
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
